name: Publish Storybook

on:
  workflow_run:
    workflows: ["Release new version"]
    types:
      - completed
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Setup
        uses: ./.github/actions/setup
        with:
          npm_token: ${{ secrets.npm_token }}
      - name: Run Build
        shell: bash
        run: yarn lerna run build --since=origin/master --include-filtered-dependencies
      - run: echo "style.monday.com" > ./packages/core/static_storybook/CNAME
        shell: bash
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
      - name: Push to Storybook's branch
        if: success()
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: "gh-pages"
          build_dir: packages/core/static_storybook
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
